# Generated by Django 3.2.4 on 2021-06-06 23:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rf_subject', models.TextField()),
                ('transportation_route', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('route_number', models.IntegerField()),
                ('carrier', models.TextField()),
                ('date_of_entry', models.DateField()),
                ('registry_number', models.TextField()),
                ('destination', models.TextField()),
                ('destination_code', models.IntegerField()),
            ],
        ),
    ]
