# Generated by Django 3.2.4 on 2021-06-07 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus_routes', '0002_alter_routemodel_route_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routemodel',
            options={'verbose_name_plural': 'routes'},
        ),
    ]
